S-21 to master
PetroRavlinko/isg-shop pull request #28
Opened 2020-11-03 14:44 UTC by obabiy

2020-11-04 09:58 UTC, vansisto approved these changes

2020-11-05 20:47 UTC, PetroRavlinko requested changes
It's it rest api. Map requests in right REST way

2020-11-05 20:47 UTC, PetroRavlinko commented on src/main/java/com/intentsg/shop/controllers/CartControllerRest.java
> +@RequestMapping("/cartRest")
Not plural

2020-11-06 10:19 UTC, IvanOlkhoviy commented on src/main/java/com/intentsg/shop/controllers/CartControllerRest.java
> +@RequestMapping("/cartRest")
Fixed

2020-11-09 07:26 UTC, PetroRavlinko commented on src/main/java/com/intentsg/shop/controllers/CartControllerRest.java
> +@RequestMapping("/cartsRest")
just carts

2023-10-10 14:14 UTC, closed without merging